cmake_minimum_required(VERSION 3.19)

set(boulderdash_known_comps static shared)
set(boulderdash_comp_static NO)
set(boulderdash_comp_shared NO)
foreach (boulderdash_comp IN LISTS ${CMAKE_FIND_PACKAGE_NAME}_FIND_COMPONENTS)
    if (boulderdash_comp IN_LIST boulderdash_known_comps)
        set(boulderdash_comp_${boulderdash_comp} YES)
    else ()
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "boulderdash does not recognize component `${boulderdash_comp}`.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif ()
endforeach ()

if (boulderdash_comp_static AND boulderdash_comp_shared)
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
        "boulderdash `static` and `shared` components are mutually exclusive.")
    set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    return()
endif ()

set(boulderdash_static_targets "${CMAKE_CURRENT_LIST_DIR}/boulderdash-static-targets.cmake")
set(boulderdash_shared_targets "${CMAKE_CURRENT_LIST_DIR}/boulderdash-shared-targets.cmake")

macro(boulderdash_load_targets type)
    if (NOT EXISTS "${boulderdash_${type}_targets}")
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "boulderdash `${type}` libraries were requested but not found.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif ()
    include("${boulderdash_${type}_targets}")
endmacro()

if (boulderdash_comp_static)
    boulderdash_load_targets(static)
elseif (boulderdash_comp_shared)
    boulderdash_load_targets(shared)
elseif (DEFINED boulderdash_SHARED_LIBS AND boulderdash_SHARED_LIBS)
    boulderdash_load_targets(shared)
elseif (DEFINED boulderdash_SHARED_LIBS AND NOT boulderdash_SHARED_LIBS)
    boulderdash_load_targets(static)
elseif (BUILD_SHARED_LIBS)
    if (EXISTS "${boulderdash_shared_targets}")
        boulderdash_load_targets(shared)
    else ()
        boulderdash_load_targets(static)
    endif ()
else ()
    if (EXISTS "${boulderdash_static_targets}")
        boulderdash_load_targets(static)
    else ()
        boulderdash_load_targets(shared)
    endif ()
endif ()
